-- Supabase Schema for Mahjong Scheduler Usage Events

-- 1. Create the usage_events table
CREATE TABLE usage_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. Enable Row Level Security (RLS) on usage_events
ALTER TABLE usage_events ENABLE ROW LEVEL SECURITY;

-- 3. Write an RLS policy for INSERT allowing the public anon role to insert rows
CREATE POLICY "Allow anon insert" 
ON usage_events 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 4. Write an RLS policy for SELECT allowing the public anon role to read rows 
--    ONLY if the request contains the header x-is-dashboard equal to 'true'.
--    This is inspected using the current_setting('request.headers', true)::json->>'x-is-dashboard' parameter.
CREATE POLICY "Allow anon select with dashboard header" 
ON usage_events 
FOR SELECT 
TO anon 
USING (
  COALESCE(NULLIF(current_setting('request.headers', true), ''), '{}')::json->>'x-is-dashboard' = 'true'
);
