-- Supabase Schema for Mahjong Scheduler Usage Events

-- 1. Create the usage_events table
CREATE TABLE usage_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    metadata jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. Enable Row Level Security (RLS) on usage_events
ALTER TABLE usage_events ENABLE ROW LEVEL SECURITY;

-- 3. Write an RLS policy for INSERT allowing the public anon role to insert rows
CREATE POLICY "Allow anon insert" 
ON usage_events 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 4. Write an RLS policy for SELECT allowing the public anon role to read rows 
--    ONLY if the request contains the header x-is-dashboard equal to 'true'.
--    This is inspected using the current_setting('request.headers', true)::json->>'x-is-dashboard' parameter.
CREATE POLICY "Allow anon select with dashboard header" 
ON usage_events 
FOR SELECT 
TO anon 
USING (
  COALESCE(NULLIF(current_setting('request.headers', true), ''), '{}')::json->>'x-is-dashboard' = 'true'
);

-- 5. Create the weekly_stats_history table
CREATE TABLE weekly_stats_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date date UNIQUE NOT NULL,
    total_bookings integer NOT NULL,
    total_cancellations integer NOT NULL,
    unique_players integer NOT NULL,
    slots_with_sets_full integer NOT NULL DEFAULT 0,
    total_slots_run integer NOT NULL DEFAULT 12,
    bookings_by_day jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 6. Enable RLS on weekly_stats_history
ALTER TABLE weekly_stats_history ENABLE ROW LEVEL SECURITY;

-- 7. Write an RLS policy for SELECT on weekly_stats_history
CREATE POLICY "Allow anon select on history with dashboard header" 
ON weekly_stats_history 
FOR SELECT 
TO anon 
USING (
  COALESCE(NULLIF(current_setting('request.headers', true), ''), '{}')::json->>'x-is-dashboard' = 'true'
);

-- 8. Write RLS policies for INSERT and UPDATE on weekly_stats_history allowing public anon role
CREATE POLICY "Allow anon insert on history" 
ON weekly_stats_history 
FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Allow anon update on history" 
ON weekly_stats_history 
FOR UPDATE 
TO anon 
USING (true);

